workflows:
    readbooks-workflow:
        name: Test Workflow
        scripts:
          - name: Build and test
            script: xcodebuild clean build test -project ReadBooks/ReadBooks.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
        max_build_duration: 120
        instance_type: mac_mini_m1
